name: NOMAD deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-prometheus:
    runs-on: ubuntu-latest
    #needs: Build
    container:
      image: theztd/nomad:latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run job
        run: |
            nomad job run \
              -var='dcs=["dc1"]' \
              -var='fqdn=rabbit-ui.fejk.net' \
              deploy.nomad
            
        env:
            NOMAD_ADDR: ${{ secrets.NOMAD_ADDR }}
            NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
